### ISSUE TITLE
Failed to get resource info from spiget.org

### ISSUE THREAD

**Issue by MattPuffin** [InventivetalentDev/AnimatedFrames#112]
## What steps will reproduce the problem?  
1. The error happens whenever a player logs in to the server
2. 
3. 

## What were you expecting to happen? What happened instead?  
I got an error
## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
4.11.2-SNAPSHOT
## What Spigot version are you using? *Type /version*  
CraftBukkit version git-Spigot-3cb9dcb-0f708cb (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
## What plugins are you using? *Type /plugins*  
CoreProtect, LuckPerms, ColoredSigns, AWD, JumpPads, PlaceholderAPI, PacketListenerApi, SetSpawn, MapManager, EasyBackup, ProtocolLib, Hibernate, MaSuiteCore, FastAsyncWorldEdit, VoidGenerator, BlocksHub, MOTDgdCommandAd, Vault, ProtocolSupport, BungeeTabListPlus, MaSuiteWarps, AnimatedFrames, GameBox, HeadDatabase, HolographicDisplays, LiteBans, Battleship, CommandSigns, Citizens, Minesweeper, UltimateChat, WhacAMole, LogicPuzzles, MP-GameBundle, HolographicExtension, 2048, CitizensCMD, WorldEdit, WorldGuard, KeepChunks
## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
https://pastebin.com/vNXrq4sa
## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
No! :)
## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
I am using bungeecord, and it has always done this, however the plugin still works fine, I just feel i should tell you about the error!

**Comment by shawngiese** [comment]
I am having this error too...
Any idea what might be causing this..
[15:44:01 INFO]: This server is running CraftBukkit version git-Spigot-f09662d-f40143e (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
[15:44:19 WARN]: [MapManager] Failed to get resource info from spiget.org
java.io.IOException: Server returned HTTP response code: 504 for URL: http://api.spiget.org/v2/resources/19198?ut=1554910999719
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1894) ~[?:1.8.0_191]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492) ~[?:1.8.0_191]
        at org.inventivetalent.update.spiget.SpigetUpdateAbstract$1.run(SpigetUpdateAbstract.java:92) [PacketListenerAPI_v3.7.2-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81) [spigot-1.13.2.jar:git-Spigot-f09662d-f40143e]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.13.2.jar:git-Spigot-f09662d-f40143e]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
[15:44:22 WARN]: [AnimatedFrames] Failed to get resource info from spiget.org
java.io.IOException: Server returned HTTP response code: 504 for URL: https://api.spiget.org/v2/resources/5583?ut=1554911002069
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1894) ~[?:1.8.0_191]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492) ~[?:1.8.0_191]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263) ~[?:1.8.0_191]
        at org.inventivetalent.animatedframes.update.SpigetUpdateAbstract$1.run(SpigetUpdateAbstract.java:92) [AnimatedFrames_v4.11.2-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81) [spigot-1.13.2.jar:git-Spigot-f09662d-f40143e]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.13.2.jar:git-Spigot-f09662d-f40143e]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]


Maybe something similar to this? https://www.spigotmc.org/threads/help-please-error.367671/

And then sometime after my server crashes.
