### ISSUE TITLE
1.14.3 Error in Console

### ISSUE THREAD

**Issue by Drynael** [InventivetalentDev/AnimatedFrames#128]
## What steps will reproduce the problem?  
1. Start 1.14.3 Paper Server
2. Login with any Character

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
latest
## What Spigot version are you using? *Type /version*  
Paper #127
## What plugins are you using? *Type /plugins*  
Plotsquared, WorldEdit, WorldGuard, ProtocolLib
## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure*

```
[14:48:48] [Craft Scheduler Thread - 22/WARN]: java.lang.NoSuchMethodException: net.minecraft.server.v1_14_R1.PacketPlayOutMap.<init>(int, byte, boolean, java.util.Collection, [B, int, int, int, int)
[14:48:48] [Craft Scheduler Thread - 22/WARN]: 	at java.lang.Class.getConstructor0(Unknown Source)
[14:48:48] [Craft Scheduler Thread - 22/WARN]: 	at java.lang.Class.getConstructor(Unknown Source)
[14:48:48] [Craft Scheduler Thread - 22/WARN]: 	at org.inventivetalent.mapmanager.MapSender.constructPacket_1_9(MapSender.java:143)
[14:48:48] [Craft Scheduler Thread - 22/WARN]: 	at org.inventivetalent.mapmanager.MapSender.constructPacket(MapSender.java:111)
[14:48:48] [Craft Scheduler Thread - 22/WARN]: 	at org.inventivetalent.mapmanager.MapSender.access$100(MapSender.java:16)
[14:48:48] [Craft Scheduler Thread - 22/WARN]: 	at org.inventivetalent.mapmanager.MapSender$2.run(MapSender.java:90)
[14:48:48] [Craft Scheduler Thread - 22/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84)
[14:48:48] [Craft Scheduler Thread - 22/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[14:48:48] [Craft Scheduler Thread - 22/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[14:48:48] [Craft Scheduler Thread - 22/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[14:48:48] [Craft Scheduler Thread - 22/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[14:48:48] [Craft Scheduler Thread - 22/WARN]: 	at java.lang.Thread.run(Unknown Source)
```
## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
nope
## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
nope

**Comment by InventivetalentDev** [comment]
Please make sure all of the dependencies of AnimatedFrames are up-to-date.
