### ISSUE TITLE
Image not shown and error in console

### ISSUE THREAD

**Issue by Ghost-chu** [InventivetalentDev/AnimatedFrames#152]
## What steps will reproduce the problem?  
1. Create a animatedframes on 1.15.2/1.15.1 paper server

## What were you expecting to happen? What happened instead?  
```
Error print in console and image only render 4 block, It should expand to whole frames.
Normal print
```
![image](https://user-images.githubusercontent.com/30802565/72985571-34dd9080-3e21-11ea-8bcf-afeafb8a1d42.png)

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
4.11.4-SNAPSHOT for AF, 1.7.5-SNAPSHOT for MM
## What Spigot version are you using? *Type /version*  
[20:42:36 INFO]: Previous version: git-Paper-34 (MC: 1.15.1)
[20:42:36 INFO]: You are running the latest version
## What plugins are you using? *Type /plugins*  
Plugins (5): AnimatedFrames*, Essentials,  MapManager*, PacketListenerApi*,  Vault

## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  

```
[20:40:41 INFO]: Ghost_chu issued server command: /afcreate test2 https://pic.mcsunnyside.com/2020/01/23/QQ20200123184110.jpg
[20:40:43 INFO]: [AnimatedFrames] Generating image data for test2...
[20:40:44 INFO]: [AnimatedFrames] Downloaded 'https://pic.mcsunnyside.com/2020/01/23/QQ20200123184110.jpg' to 'plugins\AnimatedFrames\images\aHR0cHM6Ly9waWMubWNzdW5ueXNpZGUuY29tLzIwMjAvMDEvMjMvUVEyMDIwMDEyMzE4NDExMC5qcGc='.
[20:40:44 INFO]: [AnimatedFrames] Animation length for 'test2' is zero. Creating non-animated image.
[20:40:48 WARN]: Exception in thread "pool-18-thread-1" java.lang.RuntimeException: Unexpected exception in AnimatedFrame test2
[20:40:48 WARN]:        at org.inventivetalent.animatedframes.AnimatedFrame.run(AnimatedFrame.java:286)
[20:40:48 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[20:40:48 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[20:40:48 WARN]:        at java.lang.Thread.run(Unknown Source)
[20:40:48 WARN]: Caused by: java.lang.RuntimeException: java.lang.NullPointerException
[20:40:48 WARN]:        at org.inventivetalent.mapmanager.DefaultMapWrapper.sendItemFramePacket(DefaultMapWrapper.java:380)
[20:40:48 WARN]:        at org.inventivetalent.mapmanager.DefaultMapWrapper$1.showInFrame(DefaultMapWrapper.java:228)
[20:40:48 WARN]:        at org.inventivetalent.mapmanager.DefaultMapWrapper$1.showInFrame(DefaultMapWrapper.java:233)
[20:40:48 WARN]:        at org.inventivetalent.mapmanager.MultiMapWrapper$1.showInFrames(MultiMapWrapper.java:122)
[20:40:48 WARN]:        at org.inventivetalent.animatedframes.AnimatedFrame.displayCurrentFrame(AnimatedFrame.java:298)
[20:40:48 WARN]:        at org.inventivetalent.animatedframes.AnimatedFrame.run(AnimatedFrame.java:273)
[20:40:48 WARN]:        ... 3 more
[20:40:48 WARN]: Caused by: java.lang.NullPointerException
[20:40:48 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:40:48 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[20:40:48 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[20:40:48 WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[20:40:48 WARN]:        at org.inventivetalent.mapmanager.DefaultMapWrapper.sendItemFramePacket(DefaultMapWrapper.java:357)
[20:40:48 WARN]:        ... 8 more
```

## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
No
## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
No

**Comment by InventivetalentDev** [comment]
This might be resolved by the latest update to MapManager. Please give that a try and see if the issue still occurs.

**Comment by Ghost-chu** [comment]
Confirm fixed, nice job  ^^

**Comment by Ghost-chu** [comment]
![image](https://user-images.githubusercontent.com/30802565/73041834-def8ff00-3e99-11ea-9732-883681d4ba82.png)
After chunk unload, my player walk back his home, and frame looks broken.
pause & re-play doesn't work

**Comment by Ghost-chu** [comment]
stop&play doesn't work for this frame

**Comment by Ghost-chu** [comment]
And when i use /afremove to remove this frame, **all players** got a exception messages and kicked out of server.

https://paste.ubuntu.com/p/3XTFQqH7N3/

**Comment by Ghost-chu** [comment]
I don't know this is a issue caused by ViaVersion or other some else.

**Comment by Ghost-chu** [comment]
P.S: Other images both not working, new created image still like that, pretty sure is a issue AF or MapManager

**Comment by Ghost-chu** [comment]
[latest (3).log](https://github.com/InventivetalentDev/AnimatedFrames/files/4106679/latest.3.log)

**Comment by InventivetalentDev** [comment]
Latest MapManager update should fix that aswell c:

**Comment by Ghost-chu** [comment]
![image](https://user-images.githubusercontent.com/30802565/73116044-f18f3900-3f6a-11ea-8cea-fc300fc8a781.png)

When i updated to latest MapManagaer, errors is disappear, but image no longer shown.
Nothing in console.

**Comment by Ghost-chu** [comment]
New error when frame load:
```
[17:46:37 WARN]: Exception in thread "pool-26-thread-7" java.lang.RuntimeException: Unexpected exception in AnimatedFrame WF-www.mcbbs.net
[17:46:37 WARN]: at org.inventivetalent.animatedframes.AnimatedFrame.run(AnimatedFrame.java:286)
[17:46:37 WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[17:46:37 WARN]: at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[17:46:37 WARN]: at java.base/java.lang.Thread.run(Thread.java:834)
[17:46:37 WARN]: Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 21 out of bounds for length 21
[17:46:37 WARN]: at org.inventivetalent.mapmanager.MultiMapWrapper$1.showInFrames(MultiMapWrapper.java:122)
[17:46:37 WARN]: at org.inventivetalent.animatedframes.AnimatedFrame.displayCurrentFrame(AnimatedFrame.java:298)
[17:46:37 WARN]: at org.inventivetalent.animatedframes.AnimatedFrame.run(AnimatedFrame.java:273)
[17:46:37 WARN]: ... 3 more
```
