### ISSUE TITLE
(OpenJDK13 only) Error occurred while enabling

### ISSUE THREAD

**Issue by tsao-chi** [InventivetalentDev/AnimatedFrames#159]
## What steps will reproduce the problem?  
1. install OpenJDK 13, SpigotMC and plugins
2. edit eula.txt
3. start the server

## What were you expecting to happen? What happened instead?  
```
2020-02-11T12:40:13.5096770Z [12:40:13 INFO]: [AnimatedFrames] Enabling AnimatedFrames v4.11.4-SNAPSHOT*
2020-02-11T12:40:13.5471181Z [12:40:13 WARN]: java.lang.NoSuchFieldException: modifiers
2020-02-11T12:40:13.5472700Z [12:40:13 WARN]: 	at java.base/java.lang.Class.getDeclaredField(Class.java:2412)
2020-02-11T12:40:13.5474624Z [12:40:13 WARN]: 	at org.inventivetalent.pluginannotations.AccessUtil.setAccessible(AccessUtil.java:15)
2020-02-11T12:40:13.5476320Z [12:40:13 WARN]: 	at org.inventivetalent.pluginannotations.command.AnnotatedCommand.getCommandMap(AnnotatedCommand.java:383)
2020-02-11T12:40:13.5492882Z [12:40:13 WARN]: 	at org.inventivetalent.pluginannotations.command.AnnotatedCommand.register(AnnotatedCommand.java:376)
2020-02-11T12:40:13.5495213Z [12:40:13 WARN]: 	at org.inventivetalent.pluginannotations.command.CommandAnnotations.registerCommands(CommandAnnotations.java:39)
2020-02-11T12:40:13.5501659Z [12:40:13 WARN]: 	at org.inventivetalent.pluginannotations.command.CommandAnnotations.load(CommandAnnotations.java:47)
2020-02-11T12:40:13.5504048Z [12:40:13 WARN]: 	at org.inventivetalent.animatedframes.AnimatedFramesPlugin.onEnable(AnimatedFramesPlugin.java:78)
2020-02-11T12:40:13.5505738Z [12:40:13 WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
2020-02-11T12:40:13.5511180Z [12:40:13 WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
2020-02-11T12:40:13.5513376Z [12:40:13 WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:435)
2020-02-11T12:40:13.5514846Z [12:40:13 WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:470)
2020-02-11T12:40:13.5516441Z [12:40:13 WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:384)
2020-02-11T12:40:13.5518037Z [12:40:13 WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:482)
2020-02-11T12:40:13.5519912Z [12:40:13 WARN]: 	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298)
2020-02-11T12:40:13.5522314Z [12:40:13 WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:885)
2020-02-11T12:40:13.5524652Z [12:40:13 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:830)
2020-02-11T12:40:13.5710814Z [12:40:13 ERROR]: Error occurred while enabling AnimatedFrames v4.11.4-SNAPSHOT (Is it up to date?)
2020-02-11T12:40:13.5712790Z java.lang.NullPointerException: null
2020-02-11T12:40:13.5714117Z 	at org.inventivetalent.pluginannotations.command.AnnotatedCommand.register(AnnotatedCommand.java:376) ~[?:?]
2020-02-11T12:40:13.5716506Z 	at org.inventivetalent.pluginannotations.command.CommandAnnotations.registerCommands(CommandAnnotations.java:39) ~[?:?]
2020-02-11T12:40:13.5718400Z 	at org.inventivetalent.pluginannotations.command.CommandAnnotations.load(CommandAnnotations.java:47) ~[?:?]
2020-02-11T12:40:13.5720995Z 	at org.inventivetalent.animatedframes.AnimatedFramesPlugin.onEnable(AnimatedFramesPlugin.java:78) ~[?:?]
2020-02-11T12:40:13.5723078Z 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[papermc.jar:git-Paper-102]
2020-02-11T12:40:13.5725337Z 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) ~[papermc.jar:git-Paper-102]
2020-02-11T12:40:13.5727105Z 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:435) ~[papermc.jar:git-Paper-102]
2020-02-11T12:40:13.5728838Z 	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:470) ~[papermc.jar:git-Paper-102]
2020-02-11T12:40:13.5730563Z 	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:384) ~[papermc.jar:git-Paper-102]
2020-02-11T12:40:13.5734751Z 	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:482) ~[papermc.jar:git-Paper-102]
2020-02-11T12:40:13.5736500Z 	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298) ~[papermc.jar:git-Paper-102]
2020-02-11T12:40:13.5738277Z 	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:885) ~[papermc.jar:git-Paper-102]
2020-02-11T12:40:13.5739375Z 	at java.lang.Thread.run(Thread.java:830) [?:?]
2020-02-11T12:40:13.5741636Z [12:40:13 INFO]: [AnimatedFrames] Disabling AnimatedFrames v4.11.4-SNAPSHOT
```
## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
v4.11.4-SNAPSHOT
## What Spigot version are you using? *Type /version*  
```
2020-02-11T12:39:01.0083620Z [12:39:01 INFO]: This server is running Paper version git-Paper-102 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
```
## Additional information?
working on OpenJDK11

**Comment by tsao-chi** [comment]
tes

**Comment by tsao-chi** [comment]
yes

**Comment by InventivetalentDev** [comment]
Use a different JDK
