### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by TheNety** [InventivetalentDev/AnimatedFrames#192]
## What steps will reproduce the problem?  
1. Create image
2. Wait
3. The errors may occur

## What were you expecting to happen? What happened instead?  
I sometimes get these errors
```
[14:36:55] [Craft Scheduler Thread - 666/WARN]: [AnimatedFrames] Plugin AnimatedFrames v4.12.1-SNAPSHOT generated an exception while executing task 837211
java.lang.NullPointerException: null
	at org.inventivetalent.mapmanager.DefaultMapWrapper$1.getMapId(DefaultMapWrapper.java:88) ~[?:?]
	at org.inventivetalent.mapmanager.DefaultMapManager.getOccupiedIdsFor(DefaultMapManager.java:106) ~[?:?]
	at org.inventivetalent.mapmanager.DefaultMapManager.getNextFreeIdFor(DefaultMapManager.java:120) ~[?:?]
	at org.inventivetalent.mapmanager.DefaultMapWrapper$1.addViewer(DefaultMapWrapper.java:62) ~[?:?]
	at org.inventivetalent.mapmanager.MultiMapWrapper$1$1.call(MultiMapWrapper.java:29) ~[?:?]
	at org.inventivetalent.mapmanager.MultiMapWrapper.matrixIterator(MultiMapWrapper.java:297) ~[?:?]
	at org.inventivetalent.mapmanager.MultiMapWrapper$1.addViewer(MultiMapWrapper.java:26) ~[?:?]
	at org.inventivetalent.animatedframes.AnimatedFrame.addViewer(AnimatedFrame.java:350) ~[?:?]
	at org.inventivetalent.animatedframes.PlayerListener$4.run(PlayerListener.java:112) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.4.jar:git-Paper-323]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.4.jar:git-Paper-323]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.4.jar:git-Paper-323]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_275]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_275]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
[14:36:55] [Craft Scheduler Thread - 671/WARN]: [AnimatedFrames] Plugin AnimatedFrames v4.12.1-SNAPSHOT generated an exception while executing task 837233
java.lang.NullPointerException: null
	at org.inventivetalent.mapmanager.DefaultMapWrapper$1.getMapId(DefaultMapWrapper.java:88) ~[?:?]
	at org.inventivetalent.mapmanager.DefaultMapManager.getOccupiedIdsFor(DefaultMapManager.java:106) ~[?:?]
	at org.inventivetalent.mapmanager.DefaultMapManager.getNextFreeIdFor(DefaultMapManager.java:120) ~[?:?]
	at org.inventivetalent.mapmanager.DefaultMapWrapper$1.addViewer(DefaultMapWrapper.java:62) ~[?:?]
	at org.inventivetalent.mapmanager.MultiMapWrapper$1$1.call(MultiMapWrapper.java:29) ~[?:?]
	at org.inventivetalent.mapmanager.MultiMapWrapper.matrixIterator(MultiMapWrapper.java:297) ~[?:?]
	at org.inventivetalent.mapmanager.MultiMapWrapper$1.addViewer(MultiMapWrapper.java:26) ~[?:?]
	at org.inventivetalent.animatedframes.AnimatedFrame.addViewer(AnimatedFrame.java:350) ~[?:?]
	at org.inventivetalent.animatedframes.PlayerListener$3.run(PlayerListener.java:93) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.4.jar:git-Paper-323]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.4.jar:git-Paper-323]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.4.jar:git-Paper-323]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_275]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_275]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
```

and also these
```
[AnimatedFrames] Plugin AnimatedFrames v4.12.1-SNAPSHOT generated an exception while executing task 1024926
java.lang.NullPointerException: null
[AnimatedFrames] Plugin AnimatedFrames v4.12.1-SNAPSHOT generated an exception while executing task 1217640
java.lang.NullPointerException: null
```
## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
4.12.1-SNAPSHOT

## What Spigot version are you using? *Type /version*  
Paper 1.16.4

**Comment by TheNety** [comment]
still relevant
