### ISSUE TITLE
noSuchFieldException: modifiers when loading AnimatedFrames on 1.15.2

### ISSUE THREAD

**Issue by ItsNewe** [InventivetalentDev/AnimatedFrames#202]
When loaded on Paper 1.15.2, AnimatedFrames throws a noSuchField which seems related to pluginAnnotations

Plugin version: 4.12.1-SNAPSHOT

Spigot version: 1.15.2-R0.1-SNAPSHOT

## Relevant stack trace:
```
java.lang.NoSuchFieldException: modifiers
[13:43:08 WARN]:        at java.base/java.lang.Class.getDeclaredField(Class.java:2489)
[13:43:08 WARN]:        at org.inventivetalent.pluginannotations.AccessUtil.setAccessible(AccessUtil.java:15)
[13:43:08 WARN]:        at org.inventivetalent.pluginannotations.command.AnnotatedCommand.getCommandMap(AnnotatedCommand.java:383)
[13:43:08 WARN]:        at org.inventivetalent.pluginannotations.command.AnnotatedCommand.register(AnnotatedCommand.java:376)
[13:43:08 WARN]:        at org.inventivetalent.pluginannotations.command.CommandAnnotations.registerCommands(CommandAnnotations.java:39)
[13:43:08 WARN]:        at org.inventivetalent.pluginannotations.command.CommandAnnotations.load(CommandAnnotations.java:47)
[13:43:08 WARN]:        at org.inventivetalent.animatedframes.AnimatedFramesPlugin.onEnable(AnimatedFramesPlugin.java:79)
```

**Comment by ItsNewe** [comment]
[command/AnnotatedCommand.java:25](https://github.com/InventivetalentDev/PluginAnnotations/blob/20c25f007f9c0421b70a12461328e5116ac8fb57/src/main/java/org/inventivetalent/pluginannotations/command/AnnotatedCommand.java#L383) -> [AccessUtil.java:25](https://github.com/InventivetalentDev/PluginAnnotations/blob/20c25f007f9c0421b70a12461328e5116ac8fb57/src/main/java/org/inventivetalent/pluginannotations/AccessUtil.java#L25l)

Is the Field object that is passed to PluginAnnotations faulty or is it the modifiers check's fault?

**Comment by ItsNewe** [comment]
Seeing as the problem happened with JDK13 ( #159 ), i'll clarify that JDK14 is used here
