### ISSUE TITLE
Plugin doesn't load on Spigot 1.16.5

### ISSUE THREAD

**Issue by BothimTV** [InventivetalentDev/AnimatedFrames#205]
I just got this error in the Console:

```[ERROR] Could not load 'plugins/AnimatedFrames_v4.13.0-SNAPSHOT.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: org/inventivetalent/animatedframes/AnimatedFramesPlugin has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:139) ~[spigot-1.16.5.jar:3013-Spigot-73fb609-0cd8f19]
at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:394) ~[spigot-1.16.5.jar:3013-Spigot-73fb609-0cd8f19]
at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:301) ~[spigot-1.16.5.jar:3013-Spigot-73fb609-0cd8f19]
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:382) ~[spigot-1.16.5.jar:3013-Spigot-73fb609-0cd8f19]
at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:185) ~[spigot-1.16.5.jar:3013-Spigot-73fb609-0cd8f19]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:809) ~[spigot-1.16.5.jar:3013-Spigot-73fb609-0cd8f19]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.5.jar:3013-Spigot-73fb609-0cd8f19]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.UnsupportedClassVersionError: org/inventivetalent/animatedframes/AnimatedFramesPlugin has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0
at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_212]
at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[?:1.8.0_212]
at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_212]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:163) ~[spigot-1.16.5.jar:3013-Spigot-73fb609-0cd8f19]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:96) ~[spigot-1.16.5.jar:3013-Spigot-73fb609-0cd8f19]
at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_212]
at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_212]
at java.lang.Class.forName0(Native Method) ~[?:1.8.0_212]
at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_212]
at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot-1.16.5.jar:3013-Spigot-73fb609-0cd8f19]
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot-1.16.5.jar:3013-Spigot-73fb609-0cd8f19]
... 7 more```

I use Windows 64 Bit - 2 GB Ram - Java 8

**Comment by NhProGamer** [comment]
i have the same issue

**Comment by NhProGamer** [comment]
you must use java 11 @BothimTV
