### ISSUE TITLE
FTP Filepath issues

### ISSUE THREAD

**Issue by WalrusSlayer** [InventivetalentDev/AnimatedFrames#207]
What file path do I use for FileZilla FTP?

I inputed this, but it didn't work:
/afcreate cocacola /plugins/AnimatedFrames/cocacola.gif

**Comment by WalrusSlayer** [comment]
Separately, I also get this error:
`[09:32:00 INFO]: [AnimatedFrames] Animation length for 'cocacola' is zero. Creating non-animated image.
[09:32:00 WARN]: Exception in thread "pool-32-thread-9" java.lang.RuntimeException: Unexpected exception in AnimatedFrame cocacola
[09:32:00 WARN]:        at org.inventivetalent.animatedframes.AnimatedFrame.run(AnimatedFrame.java:286)
[09:32:00 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[09:32:00 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[09:32:00 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
[09:32:00 WARN]: Caused by: java.lang.RuntimeException: Failed to read the given image. Please make sure you're using a valid source
[09:32:00 WARN]:        at org.inventivetalent.animatedframes.AnimatedFrame.run(AnimatedFrame.java:153)
[09:32:00 WARN]:        ... 3 more`

**Comment by WalrusSlayer** [comment]
Anyone know?

**Comment by WalrusSlayer** [comment]
Also, gifs do not work:
[03:27:16 INFO]: [AnimatedFrames] Animation length for 'm' is zero. Creating non-animated image.
[03:27:16 WARN]: Exception in thread "pool-32-thread-5" java.lang.RuntimeException: Unexpected exception in AnimatedFrame m
[03:27:16 WARN]:        at org.inventivetalent.animatedframes.AnimatedFrame.run(AnimatedFrame.java:286)
[03:27:16 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[03:27:16 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[03:27:16 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
[03:27:16 WARN]: Caused by: java.lang.RuntimeException: Failed to read the given image. Please make sure you're using a valid source
[03:27:16 WARN]:        at org.inventivetalent.animatedframes.AnimatedFrame.run(AnimatedFrame.java:153)
[03:27:16 WARN]:        ... 3 more

**Comment by WalrusSlayer** [comment]
hello?
