### ISSUE TITLE
/afcreate doesn't load the Frames

### ISSUE THREAD

**Issue by goreziller** [InventivetalentDev/AnimatedFrames#209]
## What steps will reproduce the problem?  
1. Creating Frame with /afcreate Test plugins/AnimatedFrames/images/Test.png
2. Try to load in
3. See Errors

## What were you expecting to happen? What happened instead?  
The Custom Frames doesn't load in as it should normally. We also checked the version but there all not outdated.

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
AnimatedFrames version 4.13.0-SNAPSHOT
MapManager version 1.8.0-SNAPSHOT
PacketListener version 3.8.0-SNAPSHOT

## What Spigot version are you using? *Type /version*  
Server is running on Paper 1.16.5 and using Java 11
![1](https://user-images.githubusercontent.com/79770947/109421035-dd233880-79d5-11eb-8287-c9d451d1b1d5.PNG)

## What plugins are you using? *Type /plugins*  
![2](https://user-images.githubusercontent.com/79770947/109421031-dac0de80-79d5-11eb-88fd-fae9f287fd65.PNG)

## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
Creating Error
https://pastebin.com/GC1xGF3U

After Restart Error
https://pastebin.com/5nFFf7ec

## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
The Client didn't crash so far

**Comment by WalrusSlayer** [comment]
I get this error:
[00:36:05 INFO]: [AnimatedFrames] Generating image data for spawn...
[00:36:05 INFO]: [AnimatedFrames] Downloaded 'https://media.giphy.com/media/zxxXYJqTlpBnO/source.gif' to 'plugins/AnimatedFrames/images/aHR0cHM6Ly9tZWRpYS5naXBoeS5jb20vbWVkaWEvenh4WFlKcVRscEJuTy9zb3VyY2UuZ2lm'.
[00:36:05 INFO]: [AnimatedFrames] Animation length for 'spawn' is zero. Creating non-animated image.
[00:36:05 WARN]: Exception in thread "pool-25-thread-5" java.lang.RuntimeException: Unexpected exception in AnimatedFrame spawn
[00:36:05 WARN]:        at org.inventivetalent.animatedframes.AnimatedFrame.run(AnimatedFrame.java:286)
[00:36:05 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[00:36:05 WARN]:        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[00:36:05 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
[00:36:05 WARN]: Caused by: java.lang.RuntimeException: Failed to read the given image. Please make sure you're using a valid source
[00:36:05 WARN]:        at org.inventivetalent.animatedframes.AnimatedFrame.run(AnimatedFrame.java:153)
[00:36:05 WARN]:        ... 3 more

**Comment by WalrusSlayer** [comment]
They're probably related
