### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by zancii** [InventivetalentDev/AnimatedFrames#219]
I installed the plugin in minecraft server, paper 1.16.5, java version is 11 and after a while errore starts reporting to me in the console.

how can i fix this?

[ERROR] .... Could not pass event PlayerInteractEvent to AnimatedFrames v4.13.0-SNAPSHOT
java.lang.NoClassDefFoundError: org.inventivetalent.reflection.minecraft.Minecraft (initialization failure)
at java.lang.J9VMInternals.initializationAlreadyFailed(Unknown Source) ~[?:?]
at org.inventivetalent.animatedframes.clickable.ClickListener.on(ClickListener.java:48) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor102.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-704]
at org.bukkit.plugin.EventExecutor$$Lambda$4255.00000000A546DDA0.execute(Unknown Source) ~[?:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-704]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-704]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:619) ~[patched_1.16.5.jar:git-Paper-704]
at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:546) ~[patched_1.16.5.jar:git-Paper-704]
at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:499) ~[patched_1.16.5.jar:git-Paper-704]
at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1705) ~[patched_1.16.5.jar:git-Paper-704]
at net.minecraft.server.v1_16_R3.PacketPlayInUseItem.a(PacketPlayInUseItem.java:32) ~[patched_1.16.5.jar:git-Paper-704]
at net.minecraft.server.v1_16_R3.PacketPlayInUseItem.a(PacketPlayInUseItem.java:10) ~[patched_1.16.5.jar:git-Paper-704]
at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-704]
at net.minecraft.server.v1_16_R3.PlayerConnectionUtils$$Lambda$5617.000000005D08D3B0.run(Unknown Source) ~[?:?]
at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-704]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-704]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-704]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-704]
at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1263) ~[patched_1.16.5.jar:git-Paper-704]
at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1256) ~[patched_1.16.5.jar:git-Paper-704]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.16.5.jar:git-Paper-704]
at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1392) ~[patched_1.16.5.jar:git-Paper-704]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1127) ~[patched_1.16.5.jar:git-Paper-704]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290) ~[patched_1.16.5.jar:git-Paper-704]
at net.minecraft.server.v1_16_R3.MinecraftServer$$Lambda$3146.00000000B9D06340.run(Unknown Source) ~[?:?]
at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.NoClassDefFoundError: sun.reflect.ConstructorAccessor
at org.inventivetalent.reflection.minecraft.Minecraft.newEnumInstance(Minecraft.java:239) ~[?:?]
at org.inventivetalent.reflection.minecraft.Minecraft$Version.getVersion(Minecraft.java:204) ~[?:?]
at org.inventivetalent.reflection.minecraft.Minecraft.<clinit>(Minecraft.java:34) ~[?:?]
at org.inventivetalent.animatedframes.clickable.ClickListener.on(ClickListener.java:48) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor102.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-704]
at org.bukkit.plugin.EventExecutor$$Lambda$4255.00000000A546DDA0.execute(Unknown Source) ~[?:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-704]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-704]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:619) ~[patched_1.16.5.jar:git-Paper-704]
at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:546) ~[patched_1.16.5.jar:git-Paper-704]
at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:509) ~[patched_1.16.5.jar:git-Paper-704]
at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:504) ~[patched_1.16.5.jar:git-Paper-704]
at net.minecraft.server.v1_16_R3.BlockPressurePlateBinary.b(BlockPressurePlateBinary.java:94) ~[patched_1.16.5.jar:git-Paper-704]
at net.minecraft.server.v1_16_R3.BlockPressurePlateAbstract.a(BlockPressurePlateAbstract.java:80) ~[patched_1.16.5.jar:git-Paper-704]
at net.minecraft.server.v1_16_R3.BlockPressurePlateAbstract.a(BlockPressurePlateAbstract.java:73) ~[patched_1.16.5.jar:git-Paper-704]
at net.minecraft.server.v1_16_R3.BlockBase$BlockData.a(BlockBase.java:626) ~[patched_1.16.5.jar:git-Paper-704]
at net.minecraft.server.v1_16_R3.Entity.checkBlockCollisions(Entity.java:1070) ~[patched_1.16.5.jar:git-Paper-704]
at net.minecraft.server.v1_16_R3.Entity.move(Entity.java:805) ~[patched_1.16.5.jar:git-Paper-704]
at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1352) ~[patched_1.16.5.jar:git-Paper-704]
at net.minecraft.server.v1_16_R3.PacketPlayInFlying.a(SourceFile:122) ~[patched_1.16.5.jar:git-Paper-704]
at net.minecraft.server.v1_16_R3.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18) ~[patched_1.16.5.jar:git-Paper 704]
at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) [patched_1.16.5.jar:git-Paper-704]
at net.minecraft.server.v1_16_R3.PlayerConnectionUtils$$Lambda$5617.000000005D08D3B0.run(Unknown Source) ~[?:?]
at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-704]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-704]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-704]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-704]
at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1263) ~[patched_1.16.5.jar:git-Paper-704]
at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1256) ~[patched_1.16.5.jar:git-Paper-704]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-704]
at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1217) ~[patched_1.16.5.jar:git-Paper-704]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1131) ~[patched_1.16.5.jar:git-Paper-704]
... 3 more
Caused by: java.lang.ClassNotFoundException: sun.reflect.ConstructorAccessor
at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:153) ~[patched_1.16.5.jar:git-Paper-704]
at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:114) ~[patched_1.16.5.jar:git-Paper-704]
at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
at org.inventivetalent.reflection.minecraft.Minecraft.newEnumInstance(Minecraft.java:239) ~[?:?]
at org.inventivetalent.reflection.minecraft.Minecraft$Version.getVersion(Minecraft.java:204) ~[?:?]
at org.inventivetalent.reflection.minecraft.Minecraft.<clinit>(Minecraft.java:34) ~[?:?]
at org.inventivetalent.animatedframes.clickable.ClickListener.on(ClickListener.java:48) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor102.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-704]
at org.bukkit.plugin.EventExecutor$$Lambda$4255.00000000A546DDA0.execute(Unknown Source) ~[?:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-704]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-704]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:619) ~[patched_1.16.5.jar:git-Paper-704]
at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:546) ~[patched_1.16.5.jar:git-Paper-704]
at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:509) ~[patched_1.16.5.jar:git-Paper-704]
at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:504) ~[patched_1.16.5.jar:git-Paper-704]
at net.minecraft.server.v1_16_R3.BlockPressurePlateBinary.b(BlockPressurePlateBinary.java:94) ~[patched_1.16.5.jar:git-Paper-704]
at net.minecraft.server.v1_16_R3.BlockPressurePlateAbstract.a(BlockPressurePlateAbstract.java:80) ~[patched_1.16.5.jar:git-Paper-704]
at net.minecraft.server.v1_16_R3.BlockPressurePlateAbstract.a(BlockPressurePlateAbstract.java:73) ~[patched_1.16.5.jar:git-Paper-704]
at net.minecraft.server.v1_16_R3.BlockBase$BlockData.a(BlockBase.java:626) ~[patched_1.16.5.jar:git-Paper-704]
at net.minecraft.server.v1_16_R3.Entity.checkBlockCollisions(Entity.java:1070) ~[patched_1.16.5.jar:git-Paper-704]
at net.minecraft.server.v1_16_R3.Entity.move(Entity.java:805) ~[patched_1.16.5.jar:git-Paper-704]
at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1352) ~[patched_1.16.5.jar:git-Paper-704]
at net.minecraft.server.v1_16_R3.PacketPlayInFlying.a(SourceFile:122) ~[patched_1.16.5.jar:git-Paper-704]
at net.minecraft.server.v1_16_R3.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-704]
at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-704]
at net.minecraft.server.v1_16_R3.PlayerConnectionUtils$$Lambda$5617.000000005D08D3B0.run(Unknown Source) ~[?:?]
at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-704]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-704]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-704]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-704]
at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1263) ~[patched_1.16.5.jar:git-Paper-704]
at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1256) ~[patched_1.16.5.jar:git-Paper-704]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-704]
at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1217) ~[patched_1.16.5.jar:git-Paper-704]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1131) ~[patched_1.16.5.jar:git-Paper-704]
... 3 more

**Comment by 6test55566** [comment]
it's hapend to ma too
idk how to fix it

**Comment by TheNety** [comment]
Also happens for me after updating to newest Paper build. This is the cause, on startup. https://gist.github.com/TheNety/517082d83f014df4dc5fe45b92f174aa
