### ISSUE TITLE
Deprecated use of CustomTimingsHandler

### ISSUE THREAD

**Issue by sebastianbinder** [InventivetalentDev/AnimatedFrames#30]
Plugin throws exception when using with PaperSpigot 1.10

```
[12:43:45 INFO]: [AnimatedFrames] The plugin is up-to-date.
[12:43:46 INFO]: [AnimatedFrames] Loading data...
[12:43:47 INFO]: [AnimatedFrames] Loaded 12 frames.
[12:43:47 WARN]: org.bukkit.plugin.AuthorNagException: Deprecated use of CustomTimingsHandler. Please Switch to Timings.of ASAP
[12:43:47 WARN]:        at org.spigotmc.CustomTimingsHandler.<init>(CustomTimingsHandler.java:58)
[12:43:47 WARN]:        at org.inventivetalent.mapmanager.TimingsHelper.createHandler(TimingsHelper.java:44)
[12:43:47 WARN]:        at org.inventivetalent.mapmanager.TimingsHelper.startTiming(TimingsHelper.java:21)
[12:43:47 WARN]:        at org.inventivetalent.animatedframes.AnimatedFrame$1.run(AnimatedFrame.java:310)
[12:43:47 WARN]:        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:58)
[12:43:47 WARN]:        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:355)
[12:43:47 WARN]:        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:792)
[12:43:47 WARN]:        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404)
[12:43:47 WARN]:        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:734)
[12:43:47 WARN]:        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:633)
[12:43:47 WARN]:        at java.lang.Thread.run(Thread.java:745)
[12:43:47 WARN]: [AnimatedFrames] Task #100 for AnimatedFrames v4.3.3 generated an exception
java.lang.RuntimeException: java.lang.IllegalArgumentException: object is not an instance of declaring class
        at org.inventivetalent.mapmanager.TimingsHelper.startTiming(TimingsHelper.java:27) ~[?:?]
        at org.inventivetalent.animatedframes.AnimatedFrame$1.run(AnimatedFrame.java:310) ~[?:?]
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.10.2.jar:git-Paper-897]
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:355) [patched_1.10.2.jar:git-Paper-897]
        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:792) [patched_1.10.2.jar:git-Paper-897]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.10.2.jar:git-Paper-897]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:734) [patched_1.10.2.jar:git-Paper-897]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:633) [patched_1.10.2.jar:git-Paper-897]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.IllegalArgumentException: object is not an instance of declaring class
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_101]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
        at org.inventivetalent.mapmanager.TimingsHelper.startTiming(TimingsHelper.java:25) ~[?:?]
        ... 8 more
```

**Comment by sebastianbinder** [comment]
Sorry, wrong plugin - MapManager is causing the problem...
