### ISSUE TITLE
Problems in AnimatedFrame

### ISSUE THREAD

**Issue by Clemdu63** [InventivetalentDev/AnimatedFrames#37]
Hello I have problems with your plugin AnimatedFrames

so I can't remove a frame, when I do the command that say Stopping animation and nothing happend
I can't create an animation ! For the plugin everything work but in minecraft I have nothing ! 

When I try to remove an animation (who don't work) I have this error

java.lang.NoSuchFieldError: v1_11_R1
at org.inventivetalent.mapmanager.DefaultMapWrapper.sendItemFramePacket(DefaultMapWrapper.java:331) ~[?:?]
at org.inventivetalent.mapmanager.DefaultMapWrapper$1.clearFrame(DefaultMapWrapper.java:231) ~[?:?]
at org.inventivetalent.mapmanager.MultiMapWrapper$1.clearFrames(MultiMapWrapper.java:149) ~[?:?]
at org.inventivetalent.animatedframes.AnimatedFrame.clearFrames(AnimatedFrame.java:361) ~[?:?]
at org.inventivetalent.animatedframes.Commands$2.run(Commands.java:240) ~[?:?]
at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:741) [spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:672) [spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:571) [spigot-1.10.jar:git-Spigot-6016ac7-10c10b3]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]

So the plugin don't work at all and I'm in spigot 1.10

when I do the command /afcreate I have that in logs :

[13:30:31] [Server thread/INFO]: Tselatra issued server command: /afcreate Spawn https://media3.giphy.com/media/zDuStFVpRJIZ2/giphy.gif
[13:30:39] [pool-24-thread-3/INFO]: [AnimatedFrames] Downloaded 'https://media3.giphy.com/media/zDuStFVpRJIZ2/giphy.gif' to 'plugins/AnimatedFrames/images/aHR0cHM6Ly9tZWRpYTMuZ2lwaHkuY29tL21lZGlhL3pEdVN0RlZwUkpJWjIvZ2lwaHkuZ2lm'.
[13:30:42] [pool-24-thread-3/WARN]: Exception in thread "
[13:30:42] [pool-24-thread-3/WARN]: pool-24-thread-3
[13:30:42] [pool-24-thread-3/WARN]: "
[13:30:42] [pool-24-thread-3/WARN]: java.lang.NoSuchFieldError: v1_11_R1
[13:30:42] [pool-24-thread-3/WARN]: at org.inventivetalent.mapmanager.DefaultMapWrapper.sendItemFramePacket(DefaultMapWrapper.java:331)
[13:30:42] [pool-24-thread-3/WARN]: at org.inventivetalent.mapmanager.DefaultMapWrapper$1.showInFrame(DefaultMapWrapper.java:216)
[13:30:42] [pool-24-thread-3/WARN]: at org.inventivetalent.mapmanager.DefaultMapWrapper$1.showInFrame(DefaultMapWrapper.java:221)
[13:30:42] [pool-24-thread-3/WARN]: at org.inventivetalent.mapmanager.MultiMapWrapper$1.showInFrames(MultiMapWrapper.java:122)
[13:30:42] [pool-24-thread-3/WARN]: at org.inventivetalent.animatedframes.AnimatedFrame.run(AnimatedFrame.java:214)
[13:30:42] [pool-24-thread-3/WARN]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[13:30:42] [pool-24-thread-3/WARN]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[13:30:42] [pool-24-thread-3/WARN]: at java.lang.Thread.run(Thread.java:745)

**Comment by InventivetalentDev** [comment]
Please use the issue template.

**Comment by Clemdu63** [comment]
I am in the issue tracker ! I have follow the link of the spigot page !!!

**Comment by InventivetalentDev** [comment]
Yeah, I can see you. Duh.

But please use the template it shows you when you create a new issue, since you need to provide important information like server version, installed plugins, etc..

**Comment by Clemdu63** [comment]
ok you can close this issue
