### ISSUE TITLE
error

### ISSUE THREAD

**Issue by angelcraft** [InventivetalentDev/AnimatedFrames#44]
## What steps will reproduce the problem?  
1. put the image
2. frames
3. 

## What were you expecting to happen? What happened instead?  
i spect to get a image but i got nothing
## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
latest

## What Spigot version are you using? *Type /version*  
1.12
## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  yeah [12:06:38 INFO]: [AnimatedFrames] Animation length for '1' is zero. Creating non-animated image.
[12:06:38 WARN]: Exception in thread "pool-14-thread-12"
[12:06:38 WARN]: java.lang.NullPointerException
[12:06:38 WARN]:        at org.inventivetalent.animatedframes.AnimatedFrame.scaleImage(AnimatedFrame.java:240)
[12:06:38 WARN]:        at org.inventivetalent.animatedframes.AnimatedFrame.run(AnimatedFrame.java:137)
[12:06:38 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[12:06:38 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[12:06:38 WARN]:        at java.lang.Thread.run(Thread.java:748)

## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
No
## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
yes

**Comment by InventivetalentDev** [comment]
Please post the image you used
