### ISSUE TITLE
Plugin doesn't load properly

### ISSUE THREAD

**Issue by TJPlaysNow** [InventivetalentDev/AnimatedFrames#5]
## What steps will reproduce the problem?  
1. Launching the plugin on CraftBukkit 1.10

## What were you expecting to happen? What happened instead?  
The plugin was supposed to launch properly, but it didn't

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
1.1.10

## What Spigot version are you using? *Type /version*  
CraftBukkit version git-Bukkit-6d3efa0 (MC: 1.10) (Implementing API version 1.10-R0.1-SNAPSHOT)

## What plugins ae you using? *Type /plugins*  
CommandPlotz, PermissionsEx, WorldEdit, ColoredSigns, Multiverse-Core, PacketListenerApi, ProtocolLib, WorldGuard, MapManager, AnimatedFrames, WebFrames, MapMenus

## Do you have an error log?
[13:46:42 INFO]: [AnimatedFrames] Enabling AnimatedFrames v4.3.1
[13:46:42 ERROR]: Error occurred while enabling AnimatedFrames v4.3.1 (Is it up to date?)
java.lang.NoClassDefFoundError: net/md_5/bungee/api/chat/BaseComponent
        at org.inventivetalent.animatedframes.AnimatedFramesPlugin.onEnable(AnimatedFramesPlugin.java:72) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[cb.jar:git-Bukkit-6d3efa0]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [cb.jar:git-Bukkit-6d3efa0]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [cb.jar:git-Bukkit-6d3efa0]
        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugin(CraftServer.java:347) [cb.jar:git-Bukkit-6d3efa0]
        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:319) [cb.jar:git-Bukkit-6d3efa0]
        at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:407) [cb.jar:git-Bukkit-6d3efa0]
        at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:372) [cb.jar:git-Bukkit-6d3efa0]
        at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:327) [cb.jar:git-Bukkit-6d3efa0]
        at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:242) [cb.jar:git-Bukkit-6d3efa0]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:517) [cb.jar:git-Bukkit-6d3efa0]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
Caused by: java.lang.ClassNotFoundException: net.md_5.bungee.api.chat.BaseComponent
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_91]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:77) ~[cb.jar:git-Bukkit-6d3efa0]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:62) ~[cb.jar:git-Bukkit-6d3efa0]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_91]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_91]
        ... 12 more

## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
No

**Comment by InventivetalentDev** [comment]
Quite simple to fix -> use Spigot, not CraftBukkit. :)

**Comment by TJPlaysNow** [comment]
It worked, haha.. Thanks but if there would be a way for you to port to CraftBukkit it would be cool
