### ISSUE TITLE
world unload null

### ISSUE THREAD

**Issue by seema84** [InventivetalentDev/AnimatedFrames#60]
after i unload a world with multiverse i get ->

[AnimatedFrames] Task #1083723 for AnimatedFrames v4.5.0-SNAPSHOT generated an exception
java.lang.NullPointerException: null
	at org.inventivetalent.animatedframes.AnimatedFrame$1.run(AnimatedFrame.java:313) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[craftbukkit.jar:git-Spigot-00128b5-558c5a3]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [craftbukkit.jar:git-Spigot-00128b5-558c5a3]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [craftbukkit.jar:git-Spigot-00128b5-558c5a3]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [craftbukkit.jar:git-Spigot-00128b5-558c5a3]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [craftbukkit.jar:git-Spigot-00128b5-558c5a3]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [craftbukkit.jar:git-Spigot-00128b5-558c5a3]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]

**Comment by melerpe** [comment]
Well, there is prob a animated frame in there. And the nullpointer means the plugin cant find it. [My suggestion, remove the frame before unloading the world]

**Comment by seema84** [comment]
or unload animated frames before a world is unloading
