### ISSUE TITLE
Error code in console [1.13]

### ISSUE THREAD

**Issue by BenjaminHoegh** [InventivetalentDev/AnimatedFrames#76]
```
30.08 08:20:34 [Server] WARN Exception in thread "pool-20-thread-6" java.lang.RuntimeException: java.lang.IllegalArgumentException: Can not set double field net.minecraft.server.v1_13_R2.AxisAlignedBB.a to net.minecraft.server.v1_13_R2.VoxelShapeCube
30.08 08:20:34 [Server] WARN at org.inventivetalent.animatedframes.boundingbox.BoundingBox.fromNMS(BoundingBox.java:246)
30.08 08:20:34 [Server] WARN at org.inventivetalent.animatedframes.boundingbox.BoundingBoxAPI.getBoundingBox(BoundingBoxAPI.java:108)
30.08 08:20:34 [Server] WARN at org.inventivetalent.animatedframes.boundingbox.BoundingBoxAPI.getAbsoluteBoundingBox(BoundingBoxAPI.java:120)
30.08 08:20:34 [Server] WARN at org.inventivetalent.frameutil.BaseFrameMapAbstract.<init>(BaseFrameMapAbstract.java:57)
30.08 08:20:34 [Server] WARN at org.inventivetalent.animatedframes.AnimatedFrame.<init>(AnimatedFrame.java:116)
30.08 08:20:34 [Server] WARN at org.inventivetalent.animatedframes.FrameManager.createFrame(FrameManager.java:111)
30.08 08:20:34 [Server] WARN at org.inventivetalent.animatedframes.Commands$1$1$1$2.run(Commands.java:180)
30.08 08:20:34 [Server] WARN at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
30.08 08:20:34 [Server] WARN at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
30.08 08:20:34 [Server] WARN at java.lang.Thread.run(Thread.java:748)
30.08 08:20:34 [Server] WARN Caused by: java.lang.IllegalArgumentException: Can not set double field net.minecraft.server.v1_13_R2.AxisAlignedBB.a to net.minecraft.server.v1_13_R2.VoxelShapeCube
30.08 08:20:34 [Server] WARN at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
30.08 08:20:34 [Server] WARN at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
30.08 08:20:34 [Server] WARN at sun.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:58)
30.08 08:20:34 [Server] WARN at sun.reflect.UnsafeDoubleFieldAccessorImpl.getDouble(UnsafeDoubleFieldAccessorImpl.java:68)
30.08 08:20:34 [Server] WARN at sun.reflect.UnsafeDoubleFieldAccessorImpl.get(UnsafeDoubleFieldAccessorImpl.java:36)
30.08 08:20:34 [Server] WARN at java.lang.reflect.Field.get(Field.java:393)
30.08 08:20:34 [Server] WARN at org.inventivetalent.animatedframes.boundingbox.BoundingBox.fromNMS(BoundingBox.java:237)
30.08 08:20:34 [Server] WARN ... 9 more
```

**Comment by InventivetalentDev** [comment]
Use the issue template.
