### ISSUE TITLE
AnimatedFrames w/PaperSpigot 1.13.2 Build 418 not working

### ISSUE THREAD

**Issue by smmmadden** [InventivetalentDev/AnimatedFrames#89]
## What steps will reproduce the problem?  
1.  Use this url to create a 4x4 image from: http://bit.ly/2PI6JRc
2.  Used this command: /afcreate Deer http://bit.ly/2PI6JRc
3.  Prompted to right-click bottom left and top right frames
4.  Got message it was loading, but console threw an exception.

## What were you expecting to happen? What happened instead?  
Having the picture actually show up.  I've gone from using a jpg to png, reduced the size from 4mb to 196kb and it still won't create the image.  What am I doing wrong?
## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
AnimatedFrames_v4.7.0-SNAPSHOT
PacketListenerAPI_v3.7.1-SNAPSHOT
MapManager_v1.5.2-SNAPSHOT
## What Spigot version are you using? *Type /version*  
PaperSpigot 1.13.2 Build 418
## What plugins are you using? *Type /plugins*  
![image](https://user-images.githubusercontent.com/10309346/47976423-50c00f80-e080-11e8-8534-49d46221c2f2.png)
## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
https://hastebin.com/kajoxusuje.md
## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
Client - no crash, no message.  
## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
Waterfall 1.13.2 Build 234
Without Bungee/Waterfall network - same builds, plugins - get the same exception.

**Comment by smmmadden** [comment]
updated to new build and was able to re-add the images (I removed the previous AnimatedFrames folder and let it generate a new one.  Everything looked fine until I restarted the server it now throws an OOM Exception for Java heap space when it shouldn't be.  I'm the only one on the server and I bumped up the MetaspaceSize to 2.5GB from 1.25GB previously and it still throws the OOM.

This is the exception:
[23:39:20] [Craft Scheduler Thread - 28/INFO]: [AnimatedFrames] Loading data...
[23:39:21] [pool-20-thread-1/INFO]: [AnimatedFrames] Loaded 3 frames.
[23:39:21] [pool-20-thread-3/INFO]: [AnimatedFrames] Reading me from cache...
[23:39:21] [pool-20-thread-2/INFO]: [AnimatedFrames] Reading deer from cache...
[23:39:21] [pool-20-thread-4/INFO]: [AnimatedFrames] Reading tmtmclogo from cache...
[23:39:21] [pool-20-thread-2/INFO]: [AnimatedFrames] Reading Frame 1/1 of deer...
[23:39:21] [pool-20-thread-4/INFO]: [AnimatedFrames] Reading Frame 1/1 of tmtmclogo...
[23:39:21] [pool-20-thread-3/INFO]: [AnimatedFrames] Reading Frame 1/1 of me...
[23:39:22] [pool-20-thread-3/WARN]: Exception in thread "pool-20-thread-3" java.lang.OutOfMemoryError: Java heap space
[23:39:22] [pool-20-thread-3/WARN]: 	at org.inventivetalent.mapmanager.ArrayImage.readFromStream(ArrayImage.java:281)
[23:39:22] [pool-20-thread-3/WARN]: 	at org.inventivetalent.animatedframes.AnimatedFrame.run(AnimatedFrame.java:206)
[23:39:22] [pool-20-thread-3/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[23:39:22] [pool-20-thread-3/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[23:39:22] [pool-20-thread-3/WARN]: 	at java.lang.Thread.run(Unknown Source)
[23:39:22] [pool-20-thread-2/WARN]: Exception in thread "pool-20-thread-2" java.lang.NegativeArraySizeException
[23:39:22] [pool-20-thread-2/WARN]: 	at org.inventivetalent.mapmanager.ArrayImage.readFromStream(ArrayImage.java:281)
[23:39:22] [pool-20-thread-2/WARN]: 	at org.inventivetalent.animatedframes.AnimatedFrame.run(AnimatedFrame.java:206)
[23:39:22] [pool-20-thread-2/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[23:39:22] [pool-20-thread-2/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[23:39:22] [pool-20-thread-2/WARN]: 	at java.lang.Thread.run(Unknown Source)
[23:39:22] [pool-20-thread-4/INFO]: [AnimatedFrames] Started 'tmtmclogo' (1/3)

This is the batch file contents used to start the server.
@echo off
title=TmTmc The Aquatic Paper Server 1.13.2
java -Xmx6G -Xms4G -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:MetaspaceSize=2048m -XX:MaxMetaspaceSize=2560m -XX:+CMSIncrementalMode -XX:+CMSIncrementalPacing -XX:+CMSParallelRemarkEnabled -XX:MaxGCPauseMillis=30 -XX:+UseBiasedLocking  -XX:+OptimizeStringConcat -XX:+UseFastAccessorMethods -XX:+AggressiveOpts -jar D:\Minecraft-Worlds\MC-Aquatic\paperclip-437-1.13.2.jar
pause

The three images I added are JPG & PNG's with no animation and <200k in size.

**Comment by smmmadden** [comment]
I just tested this on a test server and got the same results for two images used on the above.  So perhaps it is the image itself, the block configuration or they are too close to each other in the same chunk?
image one (GIF) 4 blocks wide by 3 blocks high - http://bit.ly/2S6AnOk
image two (PNG) 5 blocks wide by 4 blocks high - http://bit.ly/2PI6JRc

**Comment by smmmadden** [comment]
Tested with today's build 4.9.2 / 1.6.1 - still throws the OOM Java Heap space exception.  There is still the SpigetUpdate Invalid SemVer versions specified [491-SNAPSHOT] [ 482-SNAPSHOT] warnings present in case that helps.

**Comment by InventivetalentDev** [comment]
4.9.1 should fix the `NegativeArraySizeException` - hopefully it also helps with the heap exception

**Comment by smmmadden** [comment]
4.9.1 or 4.9.2??  Did you see my post above?

**Comment by InventivetalentDev** [comment]
there is no 4.9.2 ^^

**Comment by smmmadden** [comment]
sorry I meant 4.91

**Comment by smmmadden** [comment]
Full startup log showing the exception -> https://pastebin.com/rE6Zz2ej

**Comment by InventivetalentDev** [comment]
What are the dimensions of your images? Seems like they're a bit too big for your server's memory to handle.  

Not sure atm what causes the other exception though.

**Comment by smmmadden** [comment]
I've got 64GB's of memory on the server and allocated 6 to this instance, so it isn't memory that's the problem.  As I said above, I even increased the memory settings and it still was a problem.
The logo image is 900x600 pixels and the deer is 800x533 pixels.
They both appeared fine on the blocks I placed them on, but it wasn't until the restart that it has issues with showing them again.  So something is different between using the afcreate command and restarting the server.

**Comment by InventivetalentDev** [comment]
*dimensions in terms of blocks

**Comment by smmmadden** [comment]
I posted that above already
![image](https://user-images.githubusercontent.com/10309346/48317718-417f1b80-e5c4-11e8-977c-eca0305207cc.png)

**Comment by InventivetalentDev** [comment]
ah right, sorry.

**Comment by smmmadden** [comment]
np :-)

**Comment by InventivetalentDev** [comment]
Did you delete the cache directory again after updating? The data might be in the old format still.

**Comment by smmmadden** [comment]
I did not since it was a new feature you added, wasn't sure if it needed to be or not for restarts.  I did this time and that resolved the issue.  So is this something we'll have to do for each restart or can you add something to clear it out before continuing?
![image](https://user-images.githubusercontent.com/10309346/48317759-e8fc4e00-e5c4-11e8-9f49-c3d6278c0bf9.png)

**Comment by InventivetalentDev** [comment]
Perfect :)  
You shouldn't need to delete the cache from now on. That was just because of an issue in the file format I fixed in the last update.
