### ISSUE TITLE
Big image crashed server

### ISSUE THREAD

**Issue by LadyHaley** [InventivetalentDev/AnimatedFrames#97]
## What steps will reproduce the problem?  
1. upload big image to size of 3x5
2. crash
3. 

## What were you expecting to happen? What happened instead?  
image to appear. Crash
## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
https://i.imgur.com/bfGgAfw.png
## What Spigot version are you using? *Type /version*  
![image](https://user-images.githubusercontent.com/3754909/50875384-2d1c9b00-141c-11e9-9930-d86c323d67b1.png)

## What plugins are you using? *Type /plugins*  
![image](https://user-images.githubusercontent.com/3754909/50875400-3d347a80-141c-11e9-967c-8c702c833bc9.png)

## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
https://pastebin.com/s5tE24Gi
## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
No

**Comment by InventivetalentDev** [comment]
Could you please upload your complete server log, or at least the last ~500 lines to include the info before the crash info.

**Comment by LadyHaley** [comment]
I dont have that log anymore but I can get the log from a few hours ago because the same bug occured, give me a minute

**Comment by LadyHaley** [comment]
1st part: https://pastebin.com/wEgd0WCW
2nd part: https://pastebin.com/E2pCTUYk

**Comment by LadyHaley** [comment]
Id have sent the whole log but it was too big for pastebin

**Comment by InventivetalentDev** [comment]
Alright. I can't really pinpoint the problem, but I'll try making a few changes to hopefully stop the server from hanging. So, just to try finding the exact cause:
* Do you happen to have a lot of item frames in the world you're trying to create the frame?  
* How many animated frames have you created? (/aflist might help)

**Comment by LadyHaley** [comment]
There is currently 56 animated frames in the world right now but the first bug happened when I only had 8-10

I dont know about my other players but I use item frames to organize my storage, Here is 1 out of 2 of my storage areas. These are in the same base that I was in when I had the first crash. 
![image](https://user-images.githubusercontent.com/3754909/50961540-0c3b6f00-151c-11e9-9c39-8d9851d00b4c.png)

Let me know once the changes are live and ill be happy to test them and report back in a few days after updating if all is good, or as soon as a crash happens again.

**Comment by InventivetalentDev** [comment]
Please give version 4.11.2 a try

**Comment by LadyHaley** [comment]
https://pastebin.com/AAQQP4dQ
Here is the server log

**Comment by InventivetalentDev** [comment]
Hmm... My last changes shouldn't have affected the image loading and I can't seem to reproduce the issue.

**Comment by LadyHaley** [comment]
I think It may have been random chance that it didn't work, on the previous version the plugin would generate some kind of error that would prevent the plugin from loading but it wasn't consistent, Ill see if I can find a log later on.

**Comment by LadyHaley** [comment]
https://pastebin.com/EJHTMNka
Heres the log from it not working after a restart. I can confirm however that it does work some of the time.

**Comment by LadyHaley** [comment]
I found a restart where the plugin didnt load properly, found this error

`[11:17:39] [Server thread/ERROR]: Error occurred while enabling MapManager v1.7.2-SNAPSHOT (Is it up to date?)
java.lang.NoSuchFieldError: SEM_VER_SNAPSHOT
	at org.inventivetalent.mapmanager.MapManagerPlugin.onEnable(MapManagerPlugin.java:101) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-c7ba979]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.13.2.jar:git-Spigot-b0f4c22-c7ba979]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.13.2.jar:git-Spigot-b0f4c22-c7ba979]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:436) [spigot-1.13.2.jar:git-Spigot-b0f4c22-c7ba979]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:350) [spigot-1.13.2.jar:git-Spigot-b0f4c22-c7ba979]
	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:580) [spigot-1.13.2.jar:git-Spigot-b0f4c22-c7ba979]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:542) [spigot-1.13.2.jar:git-Spigot-b0f4c22-c7ba979]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:420) [spigot-1.13.2.jar:git-Spigot-b0f4c22-c7ba979]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294) [spigot-1.13.2.jar:git-Spigot-b0f4c22-c7ba979]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:698) [spigot-1.13.2.jar:git-Spigot-b0f4c22-c7ba979]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]`

**Comment by LadyHaley** [comment]
`[12:26:15] [Server thread/INFO]: [MapManager] Enabling MapManager v1.7.2-SNAPSHOT
[12:26:15] [Server thread/INFO]: [ReflectionHelper] I am loaded from package org.inventivetalent.reflection.minecraft
[12:26:15] [Server thread/INFO]: [ReflectionHelper] Version is v1_13_R2 (11302)
[12:26:15] [Server thread/INFO]: [MapManager] Vanilla Maps are allowed. Trying to discover occupied Map IDs...
[12:26:15] [Thread-28/INFO]: [ClearLag] Clearlag version v3.0.3 update available! Downloading...
[12:26:16] [Thread-28/INFO]: [ClearLag] Updating finished! Restart your server for files to take effect
[12:26:16] [Server thread/INFO]: [MapManager] Found 1475 occupied IDs.
[12:26:16] [Server thread/ERROR]: Error occurred while enabling MapManager v1.7.2-SNAPSHOT (Is it up to date?)
java.lang.NoSuchFieldError: SEM_VER_SNAPSHOT
	at org.inventivetalent.mapmanager.MapManagerPlugin.onEnable(MapManagerPlugin.java:101) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[spigot-1.13.2.jar:git-Spigot-b0f4c22-c7ba979]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.13.2.jar:git-Spigot-b0f4c22-c7ba979]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.13.2.jar:git-Spigot-b0f4c22-c7ba979]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:436) [spigot-1.13.2.jar:git-Spigot-b0f4c22-c7ba979]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:350) [spigot-1.13.2.jar:git-Spigot-b0f4c22-c7ba979]
	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:580) [spigot-1.13.2.jar:git-Spigot-b0f4c22-c7ba979]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:542) [spigot-1.13.2.jar:git-Spigot-b0f4c22-c7ba979]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:420) [spigot-1.13.2.jar:git-Spigot-b0f4c22-c7ba979]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294) [spigot-1.13.2.jar:git-Spigot-b0f4c22-c7ba979]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:698) [spigot-1.13.2.jar:git-Spigot-b0f4c22-c7ba979]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]`
Im still getting this error on server startup

**Comment by LadyHaley** [comment]
@InventivetalentDev

**Comment by Th3Shadowbroker** [comment]
Hi @LadyHaley,
the error-log you posted above looks familiar to me but as far as I know and as mentioned in the stack-trace, this problem is not caused by AnimatedFrames itself. The same problem was solved earlier as mentioned in issue [#30](https://github.com/InventivetalentDev/MapManager/issues/30) on the MapManager. As you can see the problem is caused by an outdated version of PluginListenerAPI. Inventive already updated the plugin and fixed this problem. If you're still using an older version of [PluginListenerAPI](https://www.spigotmc.org/resources/api-packetlistenerapi.2930/updates) than 3.7.2-SNAPSHOT please make sure to update it and report back if the problem still persists.

**Comment by LadyHaley** [comment]
oh, i didnt realize i hadnt added packet listener to my watched reasources, ill be sure to do that so i dont miss any updates in future
